repos:
  # JavaScript/TypeScript linting and formatting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.46.0
          - eslint-plugin-react@7.33.0
          - eslint-config-prettier@9.0.0
          - typescript@5.1.6
        args: [--fix]

  # Run Prettier on JavaScript/TypeScript files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|md|json)$
        args: [--write]

  # Python linting and formatting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: \.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: \.py$
        additional_dependencies:
          - flake8-docstrings==1.7.0

  # Check for large files, merge conflicts, trailing whitespace, etc.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        files: \.py$
        exclude: ^tests/
        additional_dependencies:
          - types-requests 