version: '3.8'

services:
  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web/frontend:/app
      # Exclude node_modules from volume mounting
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_BROWSER_API_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: 
      context: ./web/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web/backend:/app
    environment:
      - MONGODB_URI=mongodb+srv://goodgodgeorge:cXNSvmHkIOsHjUt4@autoshortsdb.f7asv.mongodb.net/?retryWrites=true&w=majority&appName=autoshortsdb
      - R2_ACCOUNT_ID=68b1765fe971ce074e1a3bad853b4031
      - CLOUDFLARE_R2_ACCESS_KEY_ID=ad35174d76588bef33f723cd19b25e01
      - CLOUDFLARE_R2_SECRET_ACCESS_KEY=179247cd061bed35d62efeb4d729ae5be3b281b18f8cb33ebcf804c0c6177ie
      - R2_BUCKET_NAME=autoshorts-media
      - USE_MOCK_STORAGE=False
    networks:
      - app-network

  browser-tools:
    image: node:20-slim
    command: sh -c "npm install -g @agentdeskai/browser-tools-server && npx browser-tools-server --command-port 3025"
    ports:
      - "3025:3025"
    volumes:
      - ./screenshots:/screenshots
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 